### ISSUE TITLE
PromQL autocomplete: impossible to get full labels list after comma

### ISSUE THREAD

**Issue by ahurtaud** [prometheus-community/codemirror-promql#123] opened 2021-04-02 14:06 UTC
Hello

I found a bug in the prometheus UI implementation,
When I start to type a promQL, after brackets, the full list is proposed automatically (or by hitting ctrl+space), but this is not the case starting second label filtering, the labels autocompletion is not proposed.

I tried to record this in the GIF below, at the very end I am trying to hit ctrl+space as well without success...
I would expect the labels completion dropdown

![Apr-02-2021 15-59-46](https://user-images.githubusercontent.com/25080995/113422633-547d2b00-93cd-11eb-96c4-6b4d4448aa6a.gif)

**Comment by juliusv** [comment] 2021-04-02 14:37
Thanks for the report! Hah, I didn't even know about Ctrl-Space :)

I do get completion for the second label after typing one letter of it, but that obviously doesn't allow you to list all labels then. @Nexucis can we add support for showing the full labels also after typing the first `,` in the label matchers list?

**Comment by Nexucis** [comment] 2021-04-02 15:08
yeah that's a miss definitely.
I'm just wondering if we missed it because actually lezer has a weird behavior in this particular case or if we just forget

**Comment by juliusv** [comment] 2021-04-02 16:31
@Nexucis Hmm, at least when I take this test case:

```typescript
    {
      title: 'autocomplete labelName associated to a metric',
      expr: 'metric_name{}',
      pos: 12, // cursor is between the bracket
      expectedContext: [{ kind: ContextKind.LabelName, metricName: 'metric_name' }],
    },
```

...and change it to this one:

```typescript
    {
      title: 'autocomplete second labelName associated to a metric',
      expr: 'metric_name{foo="bar",}',
      pos: 22, // cursor is after comma
      expectedContext: [{ kind: ContextKind.LabelName, metricName: 'metric_name' }],
    },
```

All the tests still pass.

**Comment by Nexucis** [comment] 2021-04-02 16:48
yeah I was doing the same, it looks like actually the issue is in the method that computes the start position.

For example, I change this unit test: 

```typescript
    {
      title: 'bracket containing a substring',
      expr: '{myL}',
      pos: 4, // cursor is between the bracket
      expectedStart: 1,
    },
```

to 
```typescript
    {
      title: 'bracket containing a substring 2',
      expr: '{myLabel="LabelValue",}',
      pos: 22, // cursor is between the bracket
      expectedStart: 22,
    },
```

And the test is failing, because the expected start position currently is `1` which is the position right after the open bracket.

So then it autocompletes the label and then filter with the value `myLabel="LabelValue",` so it returns nothing.

**Comment by juliusv** [comment] 2021-04-05 12:48
This has been fixed on the codemirror-promql side in https://github.com/prometheus-community/codemirror-promql/pull/125, but let's keep this issue open until the next codemirror-promql release is pulled into Prometheus.

**Closed** 2021-04-07 10:34 UTC
Labels: bug
