### ISSUE TITLE
How to override the `apiPrefix`

### ISSUE THREAD

**Issue by stenwolf** [prometheus-community/codemirror-promql#148] opened 2021-09-13 22:59 UTC
This is not an issue but a question, sorry if it's not the right place to post, I couldn't find anywhere else to ask.
I'm having some issue setting up the autocompletion. 

First I want to change the default endpoints for /series and /labels.
Readme specified by default it is calling  `/api/v1/labels` and  `/api/v1/series`

I have 2 endpoints for labels and series
https://mysite.com/siteapi/v1/prom/labels
https://mysite.com/siteapi/v1/prom/series

Also I'm seeing this got mentioned in the read me file
`const promQL = new PromQLExtension().setComplete({ remote: { fetchFn: myHTTPClient } })`

How do I include both of these in the fetchFn for setComplete? Or is there another way to let setComplete knows about the labels and the series endpoints?

Another question, when I tried this from the Readme, all auto suggestion seems to stop working, did I miss any config?

```
const promQL = new PromQLExtension().setComplete({
    remote: {
        cache: {
            initialMetricList: [
                'ALERTS',
                'ALERTS_FOR_STATE',
                'alertmanager_alerts',
                'alertmanager_alerts_invalid_total',
                'alertmanager_alerts_received_total',
            ]
        }
    }
})
```

**Comment by Nexucis** [comment] 2021-09-14 09:07
Hi,

> This is not an issue but a question, sorry if it's not the right place to post, I couldn't find anywhere else to ask.

it's a good place to ask :)

So with the current implementation, I don't think you can do that. The only way do to it would be to re-implement the [PrometheusClient](https://github.com/prometheus-community/codemirror-promql/blob/master/src/lang-promql/client/prometheus.ts#L39) interface which I can understand is a bit painful just for a prefix URI issue.

What could be possible would be to make configurable the[ `apiPrefix`](https://github.com/prometheus-community/codemirror-promql/blob/master/src/lang-promql/client/prometheus.ts#L39)

We are currently migrating the code to prometheus directly. It will ease the changes. This repository is becoming a mirror. So until the migration is finished, I would like to avoid to change the code. 

If you are ok with that, you could copy the code of the PrometheusClient and replace the constant `apiPrefix = '/api/v1' by yours `siteapi/v1/prom`

Once the mirror will be in place, I will change the code to make the `apiPrefix` configurable and at this moment you will be able to remove your copy of the `PrometheusClient`

> Another question, when I tried this from the Readme, all auto suggestion seems to stop working, did I miss any config?

For this part, I would suggest to open a different issue where you can describe exactly what you did. Like the step to reproduce the issue.

**Comment by Nexucis** [comment] 2021-09-14 09:24
mmm actually by providing your own implementation of `fetchFn`, you could just replace `/api/v1/` by `/siteapi/v1/prom` using some string replacement.

First parameter of `fetchFn` is the requestURI. So you need to change this parameter.

@juliusv, since it's should be quite easy to change the `RequestURI` by overriding the implementation of `fetchFn`, I'm wondering if it's worth to make the `apiPrefix` configurable like I was proposing in my first message. WDYT ?

**Comment by stenwolf** [comment] 2021-09-14 09:48
thank you for the suggestions, I don't quite understand the fetchFn implementation, does the auto complete functionality need both labels and series to work? Or do I just need to return something like an array of series for it to work?
For example if I'm using this
`const promQL = new PromQLExtension().setComplete({ remote: { fetchFn: myHTTPClient } })`

where my `myHTTPClient` is just something as simple as
```
const myHTTPClient = async () => {
    const resp = await fetch('https://mysite.com/siteapi/v1/prom/series');
    return resp;
};
```

where `resp` is something like this
[
        {
            "__name__": "name1",
            "key1": "value1",
            "key2": "value2",
        },
        {
            "__name__": "name1",
            "key1": "value1",
            "key2": "value2",
        }
]

Or is `fetchFn` something completely different, would you provide an example of what fetchFn looks like please? Thank you very much!

**Comment by Nexucis** [comment] 2021-09-14 10:09
>  does the auto complete functionality need both labels and series to work

Yes it is using both endpoints.

I would try more something like that: 

```typescript
const customFetchFn = (input: RequestInfo, init?: RequestInit): Promise<Response> => {
  if(typeof input === 'string') {
    input = input.replace('/api/v1', '/siteapi/v1/prom')
  }
  return fetch(input, init);
};
```

```typescript
const promQL = new PromQLExtension().setComplete({ url: 'https://mysite.com', remote: { fetchFn: customFetchFn } })
```

I didn't really try if my `customFetchFn` is working. But I think you can get the point :).

**Comment by juliusv** [comment] 2021-09-14 10:18
> @juliusv, since it's should be quite easy to change the RequestURI by overriding the implementation of fetchFn, I'm wondering if it's worth to make the apiPrefix configurable like I was proposing in my first message. WDYT ?

I think it's fine to make it configurable, although `/api/v1` should be standard for any backend that wants to call itself Prometheus-compatible, API-wise.

**Closed** 2021-09-24 05:52 UTC
Labels: enhancement
